version: '3.8'

services:
  postgres_sy:
    image: postgres:latest
    container_name: postgres_sy_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_sy:
    image: redis:latest
    container_name: redis_sy_cache
    restart: unless-stopped
    command: redis-server --requirepass redis
    ports:
      - "6370:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: