"""Create otp table and etc

Revision ID: 38724f89d2f2
Revises: 7b2191ddb97c
Create Date: 2025-10-09 15:29:41.102464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38724f89d2f2'
down_revision: Union[str, Sequence[str], None] = '7b2191ddb97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('hashed_otp', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_requests_id'), 'otp_requests', ['id'], unique=False)
    op.create_index(op.f('ix_otp_requests_phone_number'), 'otp_requests', ['phone_number'], unique=False)
    op.drop_table('followers')
    op.drop_table('product_likes')
    op.add_column('products', sa.Column('seller_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'products', 'sellers', ['seller_id'], ['id'])
    op.drop_column('sellers', 'brand_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('brand_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'seller_id')
    op.create_table('product_likes',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_likes_product_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('product_likes_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'product_id', name=op.f('product_likes_pkey'))
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('followed_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name=op.f('followers_followed_id_fkey')),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('followers_follower_id_fkey')),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id', name=op.f('followers_pkey'))
    )
    op.drop_index(op.f('ix_otp_requests_phone_number'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_id'), table_name='otp_requests')
    op.drop_table('otp_requests')
    # ### end Alembic commands ###
