"""add field to refresh token model

Revision ID: 4c7495ac9707
Revises: 86cd8c3b1f06
Create Date: 2025-10-11 14:36:58.286023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7495ac9707'
down_revision: Union[str, Sequence[str], None] = '86cd8c3b1f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('hashed_jti', sa.String(), nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_hashed_jti'), 'refresh_tokens', ['hashed_jti'], unique=True)
    op.drop_column('refresh_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_hashed_jti'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    op.drop_column('refresh_tokens', 'hashed_jti')
    # ### end Alembic commands ###
