"""add product interaction table

Revision ID: 8abde73941bf
Revises: 8c6916b6206d
Create Date: 2025-10-18 12:41:12.161412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abde73941bf'
down_revision: Union[str, Sequence[str], None] = '8c6916b6206d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_interactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.Enum('LIKE', 'DISLIKE', name='interactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id'),
    sa.UniqueConstraint('user_id', 'product_id', name='_user_product_uc')
    )
    op.alter_column('products', 'seller_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'seller_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('product_interactions')
    # ### end Alembic commands ###
