"""add username field to user model

Revision ID: a30bc2c358d1
Revises: d2ac7cdddbf7
Create Date: 2025-10-19 11:54:44.182704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30bc2c358d1'
down_revision: Union[str, Sequence[str], None] = 'd2ac7cdddbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('_user_product_uc', 'product_interactions', ['user_id', 'product_id'])
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_constraint('_user_product_uc', 'product_interactions', type_='unique')
    # ### end Alembic commands ###
