"""add used otp model

Revision ID: b2f32df379a4
Revises: 38724f89d2f2
Create Date: 2025-10-09 16:00:41.765283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f32df379a4'
down_revision: Union[str, Sequence[str], None] = '38724f89d2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_requests', sa.Column('used', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_requests', 'used')
    # ### end Alembic commands ###
