"""add is_default_favorites to collection

Revision ID: d2ac7cdddbf7
Revises: 8abde73941bf
Create Date: 2025-10-18 13:22:26.466982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ac7cdddbf7'
down_revision: Union[str, Sequence[str], None] = '8abde73941bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('is_default_favorites', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_collections_is_default_favorites'), 'collections', ['is_default_favorites'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_product_uc', 'product_interactions', type_='unique')
    op.drop_index(op.f('ix_collections_is_default_favorites'), table_name='collections')
    op.drop_column('collections', 'is_default_favorites')
    # ### end Alembic commands ###
